name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              otp: 24.3
              elixir: 1.12
          - pair:
              otp: 25.2
              elixir: 1.14
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5              
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix do deps.get, deps.compile, compile
      - name: Run tests
        run: |
          mix test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432